version: "2"
services:
  node:
    build: .
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    command: "node ./server/server.js"
    restart: always